### ISSUE TITLE
也是从系统通讯录呼起报错

### ISSUE THREAD

**Issue by zenkiw** [weskhen/CallKitManager#3]
你好，下载demo后，一切正常自行修正 maximumCallGroups为1
但是从系统通讯录呼起时在

- (void)starCallWithUserActivity:(NSUserActivity *)userActivity

    INInteraction *interaction = userActivity.interaction;

却出现

016-11-15 20:01:23.060317 callkitManager[619:205000] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSUserActivity interaction]: unrecognized selector sent to instance 0x17d4ab90'

完全搞不懂 也是关键字找了一整天
请教有什么环境上特别的设定吗?
感谢

**Comment by weskhen** [comment]
刚看到  这个从你报错的方法来分析  是'-[NSUserActivity interaction]: unrecognized selector sent to instance 0x17d4ab90'   这个可以说明类NSUserActivity 没有执行interaction 方法
我刚打开api看了下 有以下约束  你条件是否符合。 
@property (readonly, nullable, NS_NONATOMIC_IOSONLY) INInteraction *interaction API_AVAILABLE(macosx(10.12), ios(10.0));

**Comment by zenkiw** [comment]
感谢回覆
目前我的环境是
mac: 10.12.1
xcode: 8.1
iOS: 10.1.1

一样会报错.....

**Comment by weskhen** [comment]
@zenkiw 刚看了下需要手动添加一下Intents.Framework  如下图：

![add_intentsframework](https://cloud.githubusercontent.com/assets/13531642/20339577/274b0766-ac18-11e6-9571-40a534480e04.jpeg)

**Comment by zenkiw** [comment]
正常 太感谢了！
